// -----------------------------------------------------------------------------
// Automatically generated by 'functions_config.rb'
// DO NOT MANUALLY EDIT THIS FILE!
// -----------------------------------------------------------------------------

#include "script_component.hpp"

#define TESTS ["vectors"]

SCRIPT(test-vectors);

// ----------------------------------------------------------------------------

LOG("=== Testing Vectors ===");

{
	call compile preprocessFileLineNumbers format ["\x\cba\addons\vectors\test_%1.sqf", _x];
} forEach TESTS;

nil;
