// -----------------------------------------------------------------------------
// Automatically generated by 'functions_config.rb'
// DO NOT MANUALLY EDIT THIS FILE!
// -----------------------------------------------------------------------------

#include "script_component.hpp"

#define TESTS ["vectors"]

SCRIPT(test-vectors);

// ----------------------------------------------------------------------------

LOG("=== Testing Vectors ===");

{
    private _test = execVM format ["\x\cba\addons\vectors\test_%1.sqf", _x];
    waitUntil { scriptDone _test };
} forEach TESTS;
