// Automatically generated by 'functions_config.rb' (Sun Jun 21 18:34:18 +0100 2009)
// DO NOT MANUALLY EDIT THIS FILE!

#ifndef FUNCTIONS_CONFIG
#define FUNCTIONS_CONFIG

class CfgFunctions
{
	class CBA
	{
		class Arrays
		{
			// CBA_fnc_filter
			class filter
			{
				description = "Filter each element of an array via a function.";
				file = "\x\cba\Addons\main_arrays\fnc_filter.sqf";
			};
			// CBA_fnc_inject
			class inject
			{
				description = "Accumulates a value by passing elements through a function.";
				file = "\x\cba\Addons\main_arrays\fnc_inject.sqf";
			};
		};
	};
};

#endif // FUNCTIONS_CONFIG
