name = "Community Base Addons v1.10";
picture = "logo_cba_ca.paa";
actionName = "Website";
action = "http://dev.withsix.com/projects/cba-a3";
description = "Bugtracker: http://dev.withsix.com/projects/cca<br />Documentation: http://dev.withsix.com/projects/cba-a3";
logo = "logo_cba_ca.paa";
logoOver = "logo_cba_ca.paa";
tooltip = "Community Base Addons";
tooltipOwned = "Community Base Addons Owned";
overview = "What does the name Community Base Addons mean? It is a system that offers a range of features for addon-makers and mission designers. This includes a collection of community-built functions, an integrated keybinding system, and extend event-handler support for compatibility with other 3rd-party addons; and much much more.";
author = "CBA Team";
overviewPicture = "logo_cba_ca.paa";
overviewText = "Community Base Addons overviewText";
overviewFootnote = "<br /><br /><t color='#999999'>This content is under GPLv2 License.<br />Press <t /><t color='#19d3ff'>Left Shift + P<t /><t color='#999999'> to open the store page for more information.<t />";