// -----------------------------------------------------------------------------
// Automatically generated by 'functions_config.rb'
// DO NOT MANUALLY EDIT THIS FILE!
// -----------------------------------------------------------------------------

class CfgFunctions
{
	class CBA
	{
		class Keybinding
		{
			// CBA_fnc_getKeybind
			class getKeybind
			{
				description = "Checks if a particular mod has already registered a keybind handler for the specified action.";
				file = "\x\cba\addons\keybinding\fnc_getKeybind.sqf";
			};
			// CBA_fnc_registerKeybind
			class registerKeybind
			{
				description = "Adds or updates the keybind handler for a specified mod action, and associates a function with that keybind being pressed.";
				file = "\x\cba\addons\keybinding\fnc_registerKeybind.sqf";
			};
			// CBA_fnc_registerKeybindToFleximenu
			class registerKeybindToFleximenu
			{
				description = "Adds or updates the keybind handler for a defined Fleximenu and creates that Fleximenu.";
				file = "\x\cba\addons\keybinding\fnc_registerKeybindToFleximenu.sqf";
			};
		};
	};
};
