#include "script_component.hpp"

PREP(configureDisplayLoad);

GVAR(keyNames) = [];

GVAR(keyNames) set [0, ""];
GVAR(keyNames) set [1, localize "str_dik_escape"];
GVAR(keyNames) set [2, localize "str_dik_1"];
GVAR(keyNames) set [3, localize "str_dik_2"];
GVAR(keyNames) set [4, localize "str_dik_3"];
GVAR(keyNames) set [5, localize "str_dik_4"];
GVAR(keyNames) set [6, localize "str_dik_5"];
GVAR(keyNames) set [7, localize "str_dik_6"];
GVAR(keyNames) set [8, localize "str_dik_7"];
GVAR(keyNames) set [9, localize "str_dik_8"];
GVAR(keyNames) set [10, localize "str_dik_9"];
GVAR(keyNames) set [11, localize "str_dik_0"];
GVAR(keyNames) set [12, localize "str_dik_minus"];
GVAR(keyNames) set [13, localize "str_dik_equals"];
GVAR(keyNames) set [14, localize "str_dik_back"];
GVAR(keyNames) set [15, localize "str_dik_tab"];
GVAR(keyNames) set [16, localize "str_dik_q"];
GVAR(keyNames) set [17, localize "str_dik_w"];
GVAR(keyNames) set [18, localize "str_dik_e"];
GVAR(keyNames) set [19, localize "str_dik_r"];
GVAR(keyNames) set [20, localize "str_dik_t"];
GVAR(keyNames) set [21, localize "str_dik_y"];
GVAR(keyNames) set [22, localize "str_dik_u"];
GVAR(keyNames) set [23, localize "str_dik_i"];
GVAR(keyNames) set [24, localize "str_dik_o"];
GVAR(keyNames) set [25, localize "str_dik_p"];
GVAR(keyNames) set [26, localize "str_dik_lbracket"];
GVAR(keyNames) set [27, localize "str_dik_rbracket"];
GVAR(keyNames) set [28, localize "str_dik_return"];
GVAR(keyNames) set [29, localize "str_dik_lcontrol"];
GVAR(keyNames) set [30, localize "str_dik_a"];
GVAR(keyNames) set [31, localize "str_dik_s"];
GVAR(keyNames) set [32, localize "str_dik_d"];
GVAR(keyNames) set [33, localize "str_dik_f"];
GVAR(keyNames) set [34, localize "str_dik_g"];
GVAR(keyNames) set [35, localize "str_dik_h"];
GVAR(keyNames) set [36, localize "str_dik_j"];
GVAR(keyNames) set [37, localize "str_dik_k"];
GVAR(keyNames) set [38, localize "str_dik_l"];
GVAR(keyNames) set [39, localize "str_dik_semicolon"];
GVAR(keyNames) set [40, localize "str_dik_apostrophe"];
GVAR(keyNames) set [41, localize "str_dik_grave"];
GVAR(keyNames) set [42, localize "str_dik_lshift"];
GVAR(keyNames) set [43, localize "str_dik_backslash"];
GVAR(keyNames) set [44, localize "str_dik_z"];
GVAR(keyNames) set [45, localize "str_dik_x"];
GVAR(keyNames) set [46, localize "str_dik_c"];
GVAR(keyNames) set [47, localize "str_dik_v"];
GVAR(keyNames) set [48, localize "str_dik_b"];
GVAR(keyNames) set [49, localize "str_dik_n"];
GVAR(keyNames) set [50, localize "str_dik_m"];
GVAR(keyNames) set [51, localize "str_dik_comma"];
GVAR(keyNames) set [52, localize "str_dik_period"];
GVAR(keyNames) set [53, localize "str_dik_slash"];
GVAR(keyNames) set [54, localize "str_dik_rshift"];
GVAR(keyNames) set [55, localize "str_dik_multiply"];
GVAR(keyNames) set [56, localize "str_dik_lmenu"];
GVAR(keyNames) set [57, localize "str_dik_space"];
GVAR(keyNames) set [58, localize "str_dik_capital"];
GVAR(keyNames) set [59, localize "str_dik_f1"];
GVAR(keyNames) set [60, localize "str_dik_f2"];
GVAR(keyNames) set [61, localize "str_dik_f3"];
GVAR(keyNames) set [62, localize "str_dik_f4"];
GVAR(keyNames) set [63, localize "str_dik_f5"];
GVAR(keyNames) set [64, localize "str_dik_f6"];
GVAR(keyNames) set [65, localize "str_dik_f7"];
GVAR(keyNames) set [66, localize "str_dik_f8"];
GVAR(keyNames) set [67, localize "str_dik_f9"];
GVAR(keyNames) set [68, localize "str_dik_f10"];
GVAR(keyNames) set [69, localize "str_dik_numlock"];
GVAR(keyNames) set [70, localize "str_dik_scroll"];
GVAR(keyNames) set [71, localize "str_dik_numpad7"];
GVAR(keyNames) set [72, localize "str_dik_numpad8"];
GVAR(keyNames) set [73, localize "str_dik_numpad9"];
GVAR(keyNames) set [74, localize "str_dik_subtract"];
GVAR(keyNames) set [75, localize "str_dik_numpad4"];
GVAR(keyNames) set [76, localize "str_dik_numpad5"];
GVAR(keyNames) set [77, localize "str_dik_numpad6"];
GVAR(keyNames) set [78, localize "str_dik_add"];
GVAR(keyNames) set [79, localize "str_dik_numpad1"];
GVAR(keyNames) set [80, localize "str_dik_numpad2"];
GVAR(keyNames) set [81, localize "str_dik_numpad3"];
GVAR(keyNames) set [82, localize "str_dik_numpad0"];
GVAR(keyNames) set [83, localize "str_dik_decimal"];
GVAR(keyNames) set [86, localize "str_dik_oem_102"];
GVAR(keyNames) set [87, localize "str_dik_f11"];
GVAR(keyNames) set [88, localize "str_dik_f12"];
GVAR(keyNames) set [100, localize "str_dik_f13"];
GVAR(keyNames) set [101, localize "str_dik_f14"];
GVAR(keyNames) set [102, localize "str_dik_f15"];
GVAR(keyNames) set [112, localize "str_dik_kana"];
GVAR(keyNames) set [115, localize "str_dik_abnt_c1"];
GVAR(keyNames) set [121, localize "str_dik_convert"];
GVAR(keyNames) set [123, localize "str_dik_noconvert"];
GVAR(keyNames) set [125, localize "str_dik_yen"];
GVAR(keyNames) set [126, localize "str_dik_abnt_c2"];
GVAR(keyNames) set [141, localize "str_dik_numpadequals"];
GVAR(keyNames) set [144, localize "str_dik_prevtrack"];
GVAR(keyNames) set [145, localize "str_dik_at"];
GVAR(keyNames) set [146, localize "str_dik_colon"];
GVAR(keyNames) set [147, localize "str_dik_underline"];
GVAR(keyNames) set [148, localize "str_dik_kanji"];
GVAR(keyNames) set [149, localize "str_dik_stop"];
GVAR(keyNames) set [150, localize "str_dik_ax"];
GVAR(keyNames) set [151, localize "str_dik_unlabeled"];
GVAR(keyNames) set [153, localize "str_dik_nexttrack"];
GVAR(keyNames) set [156, localize "str_dik_numpadenter"];
GVAR(keyNames) set [157, localize "str_dik_rcontrol"];
GVAR(keyNames) set [160, localize "str_dik_mute"];
GVAR(keyNames) set [161, localize "str_dik_calculator"];
GVAR(keyNames) set [162, localize "str_dik_playpause"];
GVAR(keyNames) set [164, localize "str_dik_mediastop"];
GVAR(keyNames) set [174, localize "str_dik_volumedown"];
GVAR(keyNames) set [176, localize "str_dik_volumeup"];
GVAR(keyNames) set [178, localize "str_dik_webhome"];
GVAR(keyNames) set [179, localize "str_dik_numpadcomma"];
GVAR(keyNames) set [181, localize "str_dik_divide"];
GVAR(keyNames) set [183, localize "str_dik_sysrq"];
GVAR(keyNames) set [184, localize "str_dik_rmenu"];
GVAR(keyNames) set [197, localize "str_dik_pause"];
GVAR(keyNames) set [199, localize "str_dik_home"];
GVAR(keyNames) set [200, localize "str_dik_up"];
GVAR(keyNames) set [201, localize "str_dik_prior"];
GVAR(keyNames) set [203, localize "str_dik_left"];
GVAR(keyNames) set [205, localize "str_dik_right"];
GVAR(keyNames) set [207, localize "str_dik_end"];
GVAR(keyNames) set [208, localize "str_dik_down"];
GVAR(keyNames) set [209, localize "str_dik_next"];
GVAR(keyNames) set [210, localize "str_dik_insert"];
GVAR(keyNames) set [211, localize "str_dik_delete"];
GVAR(keyNames) set [219, localize "str_dik_lwin"];
GVAR(keyNames) set [220, localize "str_dik_rwin"];
GVAR(keyNames) set [221, localize "str_dik_apps"];
GVAR(keyNames) set [222, localize "str_dik_power"];
GVAR(keyNames) set [223, localize "str_dik_sleep"];
GVAR(keyNames) set [227, localize "str_dik_wake"];
GVAR(keyNames) set [229, localize "str_dik_websearch"];
GVAR(keyNames) set [230, localize "str_dik_webfavorites"];
GVAR(keyNames) set [231, localize "str_dik_webrefresh"];
GVAR(keyNames) set [232, localize "str_dik_webstop"];
GVAR(keyNames) set [233, localize "str_dik_webforward"];
GVAR(keyNames) set [234, localize "str_dik_webback"];
GVAR(keyNames) set [235, localize "str_dik_mycomputer"];
GVAR(keyNames) set [236, localize "str_dik_mail"];
GVAR(keyNames) set [237, localize "str_dik_mediaselect"];

GVAR(keyNames) set [327680, "Controller Button 1"];
GVAR(keyNames) set [327681, "Controller Button 2"];
GVAR(keyNames) set [327682, "Controller Button 3"];
GVAR(keyNames) set [327683, "Controller Button 4"];
GVAR(keyNames) set [327690, "Controller Button 5"];
GVAR(keyNames) set [327691, "Controller Button 6"];
GVAR(keyNames) set [327689, "Controller Button 7"];
GVAR(keyNames) set [327688, "Controller Button 8"];
GVAR(keyNames) set [327694, "Controller Button 9"];
GVAR(keyNames) set [327695, "Controller Button 10"];
GVAR(keyNames) set [327684, "Controller Direction Up"];
GVAR(keyNames) set [327685, "Controller Direction Down"];
GVAR(keyNames) set [327686, "Controller Direction Left"];
GVAR(keyNames) set [327687, "Controller Direction Right"];

// param is slow for large arrays and this makes "select" save to be used with
// out of bounds.
GVAR(keyNames) resize 1E6;

GVAR(forbiddenKeys) = ["327693","327692","327699","327703","327702","327698","327697","327701","327700","327696","327788"];
