// ----------------------------------------------------------------------------
// Automatically generated by 'functions_config.rb'
// DO NOT MANUALLY EDIT THIS FILE!
// ----------------------------------------------------------------------------

#ifndef FUNCTIONS_CONFIG
#define FUNCTIONS_CONFIG

class CfgFunctions
{
	class CBA
	{
		class Network
		{
			// CBA_fnc_remoteSay
			class remoteSay
			{
				description = "<NO DESC>";
				file = "\x\cba\Addons\main_network\fnc_remoteSay.sqf";
			};
			// CBA_fnc_remoteExecute
			class remoteExecute
			{
				description = "<NO DESC>";
				file = "\x\cba\Addons\main_network\fnc_remoteExecute.sqf";
			};
		};
	};
	class CBA_main_network
	{
		class Network
		{
			// CBA_main_network_fnc_opc
			class opc
			{
				description = "<NO DESC>";
				file = "\x\cba\Addons\main_network\fnc_opc.sqf";
			};
			// CBA_main_network_fnc_opd
			class opd
			{
				description = "<NO DESC>";
				file = "\x\cba\Addons\main_network\fnc_opd.sqf";
			};
			// CBA_main_network_fnc_sync
			class sync
			{
				description = "<NO DESC>";
				file = "\x\cba\Addons\main_network\fnc_sync.sqf";
			};
			// CBA_main_network_fnc_cv
			class cv
			{
				description = "<NO DESC>";
				file = "\x\cba\Addons\main_network\fnc_cv.sqf";
			};
			// CBA_main_network_fnc_exec
			class exec
			{
				description = "<NO DESC>";
				file = "\x\cba\Addons\main_network\fnc_exec.sqf";
			};
		};
	};
};

#endif // FUNCTIONS_CONFIG
