    class CBA_10g_9rnds {};         // 9 loose rounds
    class CBA_10g_8rnds {};         // 8 loose rounds
    class CBA_10g_7rnds {};         // 7 loose rounds
    class CBA_10g_6rnds {};         // 6 loose rounds
    class CBA_10g_5rnds {};         // 5 loose rounds
    class CBA_10g_4rnds {};         // 4 loose rounds
    class CBA_10g_3rnds {};         // 3 loose rounds
    class CBA_10g_2rnds {};         // 2 loose rounds
    class CBA_10g_1rnd {};          // 1 loose round
