// Automatically generated by 'functions_config.rb' (Sun Jun 21 18:34:18 +0100 2009)
// DO NOT MANUALLY EDIT THIS FILE!

#ifndef FUNCTIONS_CONFIG
#define FUNCTIONS_CONFIG

class CfgFunctions
{
	class CBA
	{
		class Diagnostic
		{
			// CBA_fnc_error
			class error
			{
				description = "Logs an error message to the RPT log.";
				file = "\x\cba\Addons\main_diagnostic\fnc_error.sqf";
			};
			// CBA_fnc_log
			class log
			{
				description = "Logs a message to the RPT log.";
				file = "\x\cba\Addons\main_diagnostic\fnc_log.sqf";
			};
		};
	};
};

#endif // FUNCTIONS_CONFIG
