// -----------------------------------------------------------------------------
// Automatically generated by 'functions_config.rb'
// DO NOT MANUALLY EDIT THIS FILE!
// -----------------------------------------------------------------------------
#define DEBUG_MODE_FULL
#include "script_component.hpp"

#define TESTS ["parse"]

SCRIPT(test-settings);

// ----------------------------------------------------------------------------

LOG("=== Testing Settings ===");

{
    private _test = execVM format ["\x\cba\addons\settings\test_%1.sqf", _x];
    waitUntil { scriptDone _test };
} forEach TESTS;
