// -----------------------------------------------------------------------------
// Automatically generated by 'functions_config.rb'
// DO NOT MANUALLY EDIT THIS FILE!
// -----------------------------------------------------------------------------

class CfgFunctions
{
	class CBA
	{
		class Arrays
		{
			// CBA_fnc_join
			class join
			{
				description = "Joins an array of values into a single string, joining each fragment around a separator string. Inverse of <CBA_fnc_split>.";
				file = "\x\cba\addons\arrays\fnc_join.sqf";
			};
			// CBA_fnc_filter
			class filter
			{
				description = "Filter each element of an array via a function.";
				file = "\x\cba\addons\arrays\fnc_filter.sqf";
			};
			// CBA_fnc_shuffle
			class shuffle
			{
				description = "Shuffles an array's contents into random order, returning a new array.";
				file = "\x\cba\addons\arrays\fnc_shuffle.sqf";
			};
			// CBA_fnc_inject
			class inject
			{
				description = "Accumulates a value by passing elements of an array ""through"" a function.";
				file = "\x\cba\addons\arrays\fnc_inject.sqf";
			};
		};
	};
};
