// -----------------------------------------------------------------------------
// Automatically generated by 'functions_config.rb'
// DO NOT MANUALLY EDIT THIS FILE!
// -----------------------------------------------------------------------------
#define DEBUG_MODE_FULL
#include "script_component.hpp"

#define TESTS ["filter", "inject", "join", "shuffle", "findNil", "findNull", "findTypeName", "findTypeOf", "findMax", "findMin", "insert", "standardDeviation"]
SCRIPT(test-arrays);

// ----------------------------------------------------------------------------

LOG("=== Testing Arrays ===");

{
    private _test = execVM format ["\x\cba\addons\arrays\test_%1.sqf", _x];
    waitUntil { scriptDone _test };
} forEach TESTS;
