// Automatically generated by 'functions_config.rb' (Sun Jun 21 18:34:18 +0100 2009)
// DO NOT MANUALLY EDIT THIS FILE!

#ifndef FUNCTIONS_CONFIG
#define FUNCTIONS_CONFIG

class CfgFunctions
{
	class CBA
	{
		class Events
		{
			// CBA_fnc_remoteEvent
			class remoteEvent
			{
				description = "Raises a CBA event on all machines EXCEPT the local one.";
				file = "\x\cba\Addons\main_events\fnc_remoteEvent.sqf";
			};
			// CBA_fnc_globalEvent
			class globalEvent
			{
				description = "Raises a CBA event on all machines, including the local one.";
				file = "\x\cba\Addons\main_events\fnc_globalEvent.sqf";
			};
			// CBA_fnc_localEvent
			class localEvent
			{
				description = "Raises a CBA event only on the local machine.";
				file = "\x\cba\Addons\main_events\fnc_localEvent.sqf";
			};
			// CBA_fnc_removeEventHandler
			class removeEventHandler
			{
				description = "Removes an event handler previously registered with CBA_fnc_addEventHandler.";
				file = "\x\cba\Addons\main_events\fnc_removeEventHandler.sqf";
			};
			// CBA_fnc_addEventHandler
			class addEventHandler
			{
				description = "Registers an event handler for a specific CBA event.";
				file = "\x\cba\Addons\main_events\fnc_addEventHandler.sqf";
			};
		};
	};
};

#endif // FUNCTIONS_CONFIG
