// -----------------------------------------------------------------------------
// Automatically generated by 'functions_config.rb'
// DO NOT MANUALLY EDIT THIS FILE!
// -----------------------------------------------------------------------------

class CfgFunctions
{
    class CBA
    {
        class Diagnostic
        {
            // CBA_fnc_benchmarkFunction
            class benchmarkFunction
            {
                description = "Benchmarks a function to see how long it will take to execute.";
                file = "\x\cba\addons\diagnostic\fnc_benchmarkFunction.sqf";
            };
            // CBA_fnc_debug
            class debug
            {
                description = "General Purpose Debug Message Writer";
                file = "\x\cba\addons\diagnostic\fnc_debug.sqf";
            };
            // CBA_fnc_error
            class error
            {
                description = "Logs an error message to the RPT log.";
                file = "\x\cba\addons\diagnostic\fnc_error.sqf";
            };
            // CBA_fnc_log
            class log
            {
                description = "Logs a message to the RPT log.";
                file = "\x\cba\addons\diagnostic\fnc_log.sqf";
            };
            // CBA_fnc_peek
            class peek
            {
                description = "Peek at variable on the server To receive the variable content back, you will have to [""cba_diagnostics_receive_peak"", {_this call myFunction}] call CBA_fnc_addEventHandler;";
                file = "\x\cba\addons\diagnostic\fnc_peek.sqf";
            };
            // CBA_fnc_test
            class test
            {
                description = "Runs unit tests for an addon or component.";
                file = "\x\cba\addons\diagnostic\fnc_test.sqf";
            };
            // CBA_fnc_addLogLevel
            class addLogLevel
            {
                description = "Add a system wide named log level.";
                file = "\x\cba\addons\diagnostic\fnc_addLogLevel.sqf";
            };
            // CBA_fnc_getLogLevel
            class getLogLevel
            {
                description = "Get a system wide named log level.";
                file = "\x\cba\addons\diagnostic\fnc_getLogLevel.sqf";
            };
            // CBA_fnc_removeLogLevel
            class removeLogLevel
            {
                description = "Remove a system wide named log level.";
                file = "\x\cba\addons\diagnostic\fnc_removeLogLevel.sqf";
            };
            // CBA_fnc_logDynamic
            class logDynamic
            {
                description = "Logs messages with meta information to provided log writers.";
                file = "\x\cba\addons\diagnostic\fnc_logDynamic.sqf";
            };
            // CBA_fnc_diagLogWriter
            class diagLogWriter
            {
                description = "Writes supplied message to diag_log.";
                file = "\x\cba\addons\diagnostic\fnc_diagLogWriter.sqf";
            };
            // CBA_fnc_systemChatLogWriter
            class systemChatLogWriter
            {
                description = "Writes supplied message to systemChat.";
                file = "\x\cba\addons\diagnostic\fnc_systemChatLogWriter.sqf";
            };
        };
    };
};
