// -----------------------------------------------------------------------------
// Automatically generated by 'functions_config.rb'
// DO NOT MANUALLY EDIT THIS FILE!
// -----------------------------------------------------------------------------
#define DEBUG_MODE_FULL
#include "script_component.hpp"

#define TESTS ["assertions", "parameters"]

SCRIPT(test-diagnostic);

// ----------------------------------------------------------------------------

LOG("=== Testing Diagnostic ===");

{
    private _test = execVM format ["\x\cba\addons\diagnostic\test_%1.sqf", _x];
    waitUntil { scriptDone _test };
} forEach TESTS;
