// -----------------------------------------------------------------------------
// Automatically generated by 'functions_config.rb'
// DO NOT MANUALLY EDIT THIS FILE!
// -----------------------------------------------------------------------------
#define DEBUG_MODE_FULL
#include "script_component.hpp"

#define TESTS ["config", "inventory", "weaponComponents", "ret", "macro_is_x"]

SCRIPT(test-common);

// ----------------------------------------------------------------------------

LOG("=== Testing Common ===");

{
    call compile preprocessFileLineNumbers format ["\x\cba\addons\common\test_%1.sqf", _x];
} forEach TESTS;

nil;
