// -----------------------------------------------------------------------------
// Automatically generated by 'functions_config.rb'
// DO NOT MANUALLY EDIT THIS FILE!
// -----------------------------------------------------------------------------

#include "script_component.hpp"

#define TESTS ["inheritsFrom", "macros", "parseYaml"]

SCRIPT(test-common);

// ----------------------------------------------------------------------------

LOG("=== Testing Common ===");

{
	call compile preprocessFileLineNumbers format ["\x\cba\addons\common\test_%1.sqf", _x];
} forEach TESTS;

nil;
