// -----------------------------------------------------------------------------
// Automatically generated by 'functions_config.rb'
// DO NOT MANUALLY EDIT THIS FILE!
// -----------------------------------------------------------------------------

class CfgFunctions
{
    class CBA
    {
        class Hashes
        {
            // CBA_fnc_hashCreate
            class hashCreate
            {
                description = "Check if a Hash has a value defined for a key.";
                file = "\x\cba\addons\hashes\fnc_hashCreate.sqf";
            };
            // CBA_fnc_hashEachPair
            class hashEachPair
            {
                description = "Iterate through all keys and values in a Hash.";
                file = "\x\cba\addons\hashes\fnc_hashEachPair.sqf";
            };
            // CBA_fnc_hashGet
            class hashGet
            {
                description = "Gets a value for a given key from a Hash.";
                file = "\x\cba\addons\hashes\fnc_hashGet.sqf";
            };
            // CBA_fnc_hashHasKey
            class hashHasKey
            {
                description = "Check if a Hash has a value defined for a key.";
                file = "\x\cba\addons\hashes\fnc_hashHasKey.sqf";
            };
            // CBA_fnc_hashRem
            class hashRem
            {
                description = "Removes given key from given Hash.";
                file = "\x\cba\addons\hashes\fnc_hashRem.sqf";
            };
            // CBA_fnc_hashSet
            class hashSet
            {
                description = "Sets a value for a given key in a Hash.";
                file = "\x\cba\addons\hashes\fnc_hashSet.sqf";
            };
            // CBA_fnc_isHash
            class isHash
            {
                description = "Check if a value is a Hash data structure.";
                file = "\x\cba\addons\hashes\fnc_isHash.sqf";
            };
            // CBA_fnc_testHash
            class testHash
            {
                description = "Internal Self Check. Check the RPT file for results.";
                file = "\x\cba\addons\hashes\test.sqf";
            };
            // CBA_fnc_parseYAML
            class parseYAML
            {
                description = "Parses a YAML file into a nested array/Hash structure.";
                file = "\x\cba\addons\hashes\fnc_parseYAML.sqf";
            };
        };
    };
};
