# Test file for yaml parsing.

frog: false # If true, the key settings will be ignored.
number: 1 # `

nestedHash:
    a: alpha
    b: bravo
    c: charlie              # Interesting list, eh?

nestedArray:
    - first
    - second
    -
      - 3.1
      - 3.2
      
anotherNumber: 42