// -----------------------------------------------------------------------------
// Automatically generated by 'functions_config.rb'
// DO NOT MANUALLY EDIT THIS FILE!
// -----------------------------------------------------------------------------

#include "script_component.hpp"

#define TESTS ["compatibleItems.inc"]

SCRIPT(test-jr);

// ----------------------------------------------------------------------------

LOG("=== Testing JR ===");

{
    private _test = execVM format ["\x\cba\addons\jr\test_%1.sqf", _x];
    waitUntil { scriptDone _test };
} forEach TESTS;
