// -----------------------------------------------------------------------------
// Automatically generated by 'functions_config.rb'
// DO NOT MANUALLY EDIT THIS FILE!
// -----------------------------------------------------------------------------

#include "script_component.hpp"

#define TESTS ["compatibleItems"]

SCRIPT(test-jr);

// ----------------------------------------------------------------------------

LOG("=== Testing JR ===");

{
    call compile preprocessFileLineNumbers format ["\x\cba\addons\jr\test_%1.sqf", _x];
} forEach TESTS;

nil;
