#!/bin/sh

NATURALDOCS=`which NaturalDocs 2>/dev/null || which naturaldocs 2>/dev/null`
# Debian package uses a script wrapper that is lower case

if [ -z $NATURALDOCS ]
then
  echo "Could not find NaturalDocs in the PATH. Install it or adjust the PATH environment variable."
  exit 1
fi

echo "\n=== Compiling documentation ===\n"
if [ ! -d ../docs ]
then
  mkdir ../docs
fi
cp overview.txt CBA_logo_large.png ../addons

# Move the documented, but internal-only functions out of the way
# while compiling the documentation
cp -a ../addons/xeh /tmp/
rm -r ../addons/xeh/*
cp -a /tmp/xeh/fnc_addClassEventHandler.sqf ../addons/xeh
cp -a /tmp/xeh/fnc_compileEventHandlers.sqf ../addons/xeh
cp -a /tmp/xeh/fnc_compileFunction.sqf ../addons/xeh
cp -a /tmp/xeh/fnc_isRecompileEnabled.sqf ../addons/xeh
cp -a /tmp/xeh/fnc_isScheduled.sqf ../addons/xeh

$NATURALDOCS -r -i "../addons" -o HTML "../docs" -p "ndocs-project" -s Default cba
find ../addons/ \
	-name overview.txt -o \
	-name CBA_logo_large.png | \
xargs rm

# Restore xeh
cp -a /tmp/xeh/* ../addons/xeh/
rm -rf /tmp/xeh

echo "\n=== Packaging documentation ===\n"
rm -f ../store/function_library.tar
fakeroot tar -C ../ -cf ../store/function_library.tar docs

exit 0
