#!/bin/bash

docker build . -t natural-docs-1-52 -f tools/natural-docs.dockerfile

docker run -d -i -t -v "$(pwd)/:/cba" --name CBA_A3_Make_Docs natural-docs-1-52

docker exec CBA_A3_Make_Docs apt install fakeroot -y;
docker exec CBA_A3_Make_Docs chmod +x cba/tools/make_docs
docker exec CBA_A3_Make_Docs /bin/bash -c "cd cba/tools/; ./make_docs"

docker kill CBA_A3_Make_Docs

docker rm CBA_A3_Make_Docs