// -----------------------------------------------------------------------------
// Automatically generated by 'functions_config.rb'
// DO NOT MANUALLY EDIT THIS FILE!
// -----------------------------------------------------------------------------

class CfgFunctions
{
	class CBA
	{
		class Network
		{
			// CBA_fnc_remoteSay
			class remoteSay
			{
				description = "<NO DESC>";
				file = "\x\cba\addons\network\fnc_remoteSay.sqf";
			};
			// CBA_fnc_remoteExecute
			class remoteExecute
			{
				description = "<NO DESC>";
				file = "\x\cba\addons\network\fnc_remoteExecute.sqf";
			};
		};
	};
};
