// ----------------------------------------------------------------------------
// Automatically generated by 'functions_config.rb'
// DO NOT MANUALLY EDIT THIS FILE!
// ----------------------------------------------------------------------------

#ifndef FUNCTIONS_CONFIG
#define FUNCTIONS_CONFIG

class CfgFunctions
{
	class CBA
	{
		class Network
		{
			// CBA_fnc_remoteSay
			class remoteSay
			{
				description = "<NO DESC>";
				file = "\x\cba\Addons\network\fnc_remoteSay.sqf";
			};
			// CBA_fnc_remoteExecute
			class remoteExecute
			{
				description = "<NO DESC>";
				file = "\x\cba\Addons\network\fnc_remoteExecute.sqf";
			};
		};
	};
};

#endif // FUNCTIONS_CONFIG
