// -----------------------------------------------------------------------------
// Automatically generated by 'functions_config.rb'
// DO NOT MANUALLY EDIT THIS FILE!
// -----------------------------------------------------------------------------

class CfgFunctions
{
	class CBA
	{
		class Network
		{
			// CBA_fnc_globalExecute
			class globalExecute
			{
				description = "<NO DESC>";
				file = "\x\cba\addons\network\fnc_globalExecute.sqf";
			};
			// CBA_fnc_globalSay
			class globalSay
			{
				description = "<NO DESC>";
				file = "\x\cba\addons\network\fnc_globalSay.sqf";
			};
		};
	};
};
