// -----------------------------------------------------------------------------
// Automatically generated by 'functions_config.rb'
// DO NOT MANUALLY EDIT THIS FILE!
// -----------------------------------------------------------------------------
#define DEBUG_MODE_FULL
#include "script_component.hpp"

#define TESTS ["network"]

SCRIPT(test-network);

// ----------------------------------------------------------------------------

LOG("=== Testing Network ===");

{
    private _test = execVM format ["\x\cba\addons\network\test_%1.sqf", _x];
    waitUntil { scriptDone _test };
} forEach TESTS;
