// ----------------------------------------------------------------------------
// Automatically generated by 'functions_config.rb'
// DO NOT MANUALLY EDIT THIS FILE!
// ----------------------------------------------------------------------------

#ifndef FUNCTIONS_CONFIG
#define FUNCTIONS_CONFIG

class CfgFunctions
{
	class CBA
	{
		class Events
		{
			// CBA_fnc_addKeyHandler
			class addKeyHandler
			{
				description = "<NO DESC>";
				file = "\x\cba\Addons\events\fnc_addKeyHandler.sqf";
			};
			// CBA_fnc_addActionHandler
			class addActionHandler
			{
				description = "<NO DESC>";
				file = "\x\cba\Addons\events\fnc_addActionHandler.sqf";
			};
			// CBA_fnc_remoteEvent
			class remoteEvent
			{
				description = "Raises a CBA event on all machines EXCEPT the local one.";
				file = "\x\cba\Addons\events\fnc_remoteEvent.sqf";
			};
			// CBA_fnc_addKeyHandlerFromConfig
			class addKeyHandlerFromConfig
			{
				description = "<NO DESC>";
				file = "\x\cba\Addons\events\fnc_addKeyHandlerFromConfig.sqf";
			};
			// CBA_fnc_addActionHandlerFromConfig
			class addActionHandlerFromConfig
			{
				description = "<NO DESC>";
				file = "\x\cba\Addons\events\fnc_addActionHandlerFromConfig.sqf";
			};
			// CBA_fnc_actionHandler
			class actionHandler
			{
				description = "<NO DESC>";
				file = "\x\cba\Addons\events\fnc_actionHandler.sqf";
			};
			// CBA_fnc_readKeyFromConfig
			class readKeyFromConfig
			{
				description = "<NO DESC>";
				file = "\x\cba\Addons\events\fnc_readKeyFromConfig.sqf";
			};
			// CBA_fnc_keyHandler
			class keyHandler
			{
				description = "<NO DESC>";
				file = "\x\cba\Addons\events\fnc_keyHandler.sqf";
			};
			// CBA_fnc_globalEvent
			class globalEvent
			{
				description = "Raises a CBA event on all machines, including the local one.";
				file = "\x\cba\Addons\events\fnc_globalEvent.sqf";
			};
			// CBA_fnc_readActionFromConfig
			class readActionFromConfig
			{
				description = "<NO DESC>";
				file = "\x\cba\Addons\events\fnc_readActionFromConfig.sqf";
			};
			// CBA_fnc_localEvent
			class localEvent
			{
				description = "Raises a CBA event only on the local machine.";
				file = "\x\cba\Addons\events\fnc_localEvent.sqf";
			};
			// CBA_fnc_removeEventHandler
			class removeEventHandler
			{
				description = "Removes an event handler previously registered with CBA_fnc_addEventHandler.";
				file = "\x\cba\Addons\events\fnc_removeEventHandler.sqf";
			};
			// CBA_fnc_addEventHandler
			class addEventHandler
			{
				description = "Registers an event handler for a specific CBA event.";
				file = "\x\cba\Addons\events\fnc_addEventHandler.sqf";
			};
		};
	};
};

#endif // FUNCTIONS_CONFIG
