// -----------------------------------------------------------------------------
// Automatically generated by 'functions_config.rb'
// DO NOT MANUALLY EDIT THIS FILE!
// -----------------------------------------------------------------------------
#define DEBUG_MODE_FULL
#include "script_component.hpp"

#define TESTS ["globalEventJIP"]

SCRIPT(test-events);

// ----------------------------------------------------------------------------

LOG("=== Testing Events ===");

{
    0 spawn compile preprocessFileLineNumbers format ["\x\cba\addons\events\test_%1.sqf", _x];
} forEach TESTS;

nil
